### ISSUE TITLE
COSMOS Integration

### ISSUE THREAD

**Issue by dinkelk** [lasp/adamant#15]
New Feature

Adamant integration with COSMOS (https://github.com/OpenC3/cosmos) command and control system. This includes:

1. Generators for command, telemetry, and event definitions that allow COSMOS to decode telemetry and events and send commands
2. Update documentation in User Guide
3. Update tutorials for Pico and Linux examples

**Comment by dinkelk** [comment]
@Jbsco is starting work on this

**Comment by Jbsco** [comment]
Baseline functionality is mostly complete with generators for Cosmos plugins implemented by #21.
Tutorial for Linux example is in place at [adamant_example #18](https://github.com/lasp/adamant_example/pull/18).
